
object Versions {
    const val lifecycleRuntimeKtx = "2.8.7"
    const val lifecycleViewModelKtx = "2.6.1"
    const val appCompat = "1.7.0"
    const val hilt = "2.48"
    const val hiltCompiler = "2.28-alpha"
    const val navigationCompose = "2.8.4"
    const val retrofit = "2.9.0"
    const val okHttp = "4.11.0"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.15.0"
    const val moshiConverter = "2.9.0"
    const val loggingInterceptor = "4.11.0"
    const val coroutines = "1.7.3"
    const val coreSplashscreen = "1.0.1"
    const val coilCompose = "2.4.0"
    const val agp = "8.7.1"
    const val hiltAndroidCompiler = "2.52"
    const val kotlin = "2.0.0"
    const val coreKtx = "1.15.0"
    const val junit = "4.13.2"
    const val junitVersion = "1.2.1"
    const val espressoCore = "3.6.1"
    const val appcompat = "1.7.0"
    const val material = "1.12.0"
    const val constraintlayout = "2.2.0"
    const val lifecycleLivedataKtx = "2.8.7"
    const val lifecycleViewmodelKtx = "2.8.7"
    const val fragmentKtx = "1.5.6"
    const val navigationFragmentKtx = "2.8.4"
    const val navigationUiKtx = "2.8.4"
    const val legacySupportV4 = "1.0.0"
    const val runtime = "2.1.0"
    const val foundationAndroid = "1.7.6"
    const val material3Android = "1.3.1"
    const val roomCommon = "2.6.1"
    const val roomKtx = "2.6.1"
    const val uiToolingPreviewAndroid = "1.7.6"
    const val activityCompose = "1.10.0"
    const val composeBom = "2025.01.00"
    const val materialIconsExtended = "1.7.6"
    const val hiltLifecycleViewmodel = "1.0.0-alpha03"
    const val hiltNavigationCompose = "1.2.0"
    const val viewModelCompose = "2.8.7"

}
